### ISSUE TITLE
Urgent: http redirect url no longer supported

### ISSUE THREAD

**Issue by f8vze** [shu-go/slack-file#1]
This page: 
https://shuheikubota.github.io/soft/slack-file/

Shows creating a http based redirect url. However, http based url's can no longer be entered in Slack settings:

![image](https://user-images.githubusercontent.com/84421262/186550972-a84afe04-99dd-4038-9ed7-6ab72cfab7a5.png)

The "Add" button cannot be clicked.

Using `https://localhost:7878` instead allows the redirect url to be added, but the app does not work then, as then we get:

![image](https://user-images.githubusercontent.com/84421262/186551157-01baa0e1-20d8-43a9-b48b-1c2ae7b8fc1c.png)

When using `./slack-file auth`.

Can this be fixed asap please?

**Comment by ShuheiKubota** [comment]
@f8vze
Thank you!

I added http**s**://localhost code.
Try 0.4.5.

Two files (./cert.pem and ./key.pem) are generated and placed in your working directory.
After `slack-file auth` step, they are no longer used.

**Comment by f8vze** [comment]
@ShuheiKubota Thank you for the fast turnaround! I now get:
```
$ ./slack-file auth ...credentials...
Opening in existing browser session.
2022/08/25 18:47:43 wrote ./cert.pem
2022/08/25 18:47:43 wrote ./key.pem
2022/08/25 18:47:50 http: TLS handshake error from [::1]:34964: remote error: tls: unknown certificate
2022/08/25 18:47:53 http: TLS handshake error from [::1]:34968: remote error: tls: unknown certificate
$ ./slack-file ls *.pdf
missing_scope
$ 
```

**Comment by ShuheiKubota** [comment]
@f8vze
Could you try "Reinstall to Workspace", please?

**Comment by f8vze** [comment]
Sorry not sure what that means? i.e. I just use the downloaded binary? Thank you

**Comment by ShuheiKubota** [comment]
@f8vze
After adding permissions (files:read, files:write), you need to do the action bellow:
1. in the page "OAuth & Permissions",
2. in the section "OAuth Tokens for Your Workspace",
3. push "Reinstall to Workspace"

The action **is missing in my instruction page**, sorry.

Then, try `slack-file ls`
